import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';

import { AppButton } from '@/components/app-button';
import { AppCard } from '@/components/app-card';
import { AppHeader } from '@/components/app-header';
import { AppScreen } from '@/components/app-screen';
import { StatusBadge } from '@/components/status-badge';
import { AppColors } from '@/constants/app-theme';
import { quotes } from '@/mocks/quotes';
import { currentCompany } from '@/mocks/account';
import { formatCurrency, getQuoteSubtotal } from '@/utils/format';

export default function QuoteDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const quote = quotes.find((item) => item.id === id) ?? quotes[0];
  const subtotal = getQuoteSubtotal(quote.items);
  const total = subtotal - quote.discount;
  return <AppScreen header={<AppHeader back title={`Orçamento #${quote.number}`} subtitle="Documento comercial" />}><View style={styles.page}><AppCard style={styles.document}><View style={styles.documentTop}><View><Text style={styles.documentTitle}>ORÇAMENTO</Text><Text style={styles.company}>{currentCompany.name}</Text></View><StatusBadge status={quote.status} /></View><View style={styles.info}><Info label="Cliente" value={quote.clientName} /><Info label="Data" value={quote.createdAt} /><Info label="Validade" value={quote.validUntil} /></View><View style={styles.tableHeader}><Text style={[styles.tableHeaderText, styles.itemColumn]}>Produto</Text><Text style={styles.tableHeaderText}>Qtd.</Text><Text style={styles.tableHeaderText}>Subtotal</Text></View>{quote.items.map((item) => <View key={item.id} style={styles.itemRow}><View style={styles.itemColumn}><Text style={styles.itemName}>{item.productName}</Text><Text style={styles.itemUnit}>{formatCurrency(item.unitPrice)} un.</Text></View><Text style={styles.itemText}>{item.quantity}</Text><Text style={styles.itemText}>{formatCurrency(item.quantity * item.unitPrice)}</Text></View>)}<View style={styles.totals}><TotalLine label="Subtotal" value={formatCurrency(subtotal)} /><TotalLine label="Desconto" value={`− ${formatCurrency(quote.discount)}`} /><View style={styles.totalLine}><Text style={styles.totalLabel}>TOTAL</Text><Text style={styles.totalValue}>{formatCurrency(total)}</Text></View></View>{quote.notes ? <View style={styles.notes}><Text style={styles.notesTitle}>Observações</Text><Text style={styles.notesCopy}>{quote.notes}</Text></View> : null}</AppCard><AppButton label="Gerenciar itens" onPress={() => router.push('/orcamentos/itens' as never)} variant="secondary" /><View style={styles.actions}><AppButton label="Gerar PDF" onPress={() => router.push('/compartilhar' as never)} style={styles.actionButton} /><AppButton label="Compartilhar" onPress={() => router.push('/compartilhar' as never)} style={styles.actionButton} variant="secondary" /></View></View></AppScreen>;
}

function Info({ label, value }: { label: string; value: string }) { return <View><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
function TotalLine({ label, value }: { label: string; value: string }) { return <View style={styles.totalItem}><Text style={styles.totalItemLabel}>{label}</Text><Text style={styles.totalItemValue}>{value}</Text></View>; }

const styles = StyleSheet.create({ page: { gap: 13 }, document: { gap: 18 }, documentTop: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' }, documentTitle: { color: AppColors.primaryDark, fontSize: 20, fontWeight: '900', letterSpacing: 0.7 }, company: { color: AppColors.muted, fontSize: 13, marginTop: 4 }, info: { borderBottomColor: AppColors.line, borderBottomWidth: 1, borderTopColor: AppColors.line, borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 13 }, infoLabel: { color: AppColors.muted, fontSize: 10, fontWeight: '700' }, infoValue: { color: AppColors.ink, fontSize: 12, fontWeight: '800', marginTop: 4, maxWidth: 105 }, tableHeader: { flexDirection: 'row' }, tableHeaderText: { color: AppColors.muted, fontSize: 10, fontWeight: '800', textAlign: 'right', width: 75 }, itemColumn: { flex: 1, textAlign: 'left', width: 'auto' }, itemRow: { alignItems: 'flex-start', flexDirection: 'row', paddingVertical: 3 }, itemName: { color: AppColors.ink, fontSize: 12, fontWeight: '700' }, itemUnit: { color: AppColors.muted, fontSize: 10, marginTop: 3 }, itemText: { color: AppColors.ink, fontSize: 11, paddingTop: 2, textAlign: 'right', width: 75 }, totals: { borderTopColor: AppColors.line, borderTopWidth: 1, gap: 8, paddingTop: 13 }, totalItem: { flexDirection: 'row', justifyContent: 'space-between' }, totalItemLabel: { color: AppColors.muted, fontSize: 12 }, totalItemValue: { color: AppColors.ink, fontSize: 12, fontWeight: '700' }, totalLine: { borderTopColor: AppColors.line, borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 4, paddingTop: 12 }, totalLabel: { color: AppColors.primaryDark, fontSize: 14, fontWeight: '900' }, totalValue: { color: AppColors.primaryDark, fontSize: 19, fontWeight: '900' }, notes: { backgroundColor: AppColors.infoSoft, borderRadius: 10, padding: 12 }, notesTitle: { color: AppColors.primaryDark, fontSize: 11, fontWeight: '800' }, notesCopy: { color: AppColors.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, actions: { flexDirection: 'row', gap: 10 }, actionButton: { flex: 1, minWidth: 0 } });
